name: Build 4 - Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:7.5-jdk17
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        for app in messaging calling gallery fileexplorer keyboard; do
          cd $app && gradle assembleDebug && cd ..
        done
    - name: Upload
      uses: actions/upload-artifact@v4
      with: {name: apk4, path: '**/*.apk'}
