name: Build 9 - Nix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      run: curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
    - name: Build
      run: |
        for app in messaging calling gallery fileexplorer keyboard; do
          cd $app && nix-shell -p gradle --run "gradle assembleDebug" && cd ..
        done
    - name: Upload
      uses: actions/upload-artifact@v4
      with: {name: apk9, path: '**/*.apk'}
